export const ActionType = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  SET_CATEGORY: "SET_CATEGORY",
  SET_CATEGORY_PRODUCT: "SET_CATEGORY_PRODUCT",
  REMOVE_CATEGORY_PRODUCT: "REMOVE_CATEGORY_PRODUCT",
};
